Import Pandas at first to be able to load data to a dataframe:

In [7]:
import pandas as pd

# 1. Extract Data

## 1.1 Employed Data import

In [8]:
google_sheet_id = '1VCkHwBjJGRJ21asd9pxW4_0z2PWuKhbLR3gUHm-p4GI'

In [9]:
url='https://docs.google.com/spreadsheets/d/' + google_sheet_id + '/export?format=xlsx'

In [10]:
enrollies = pd.read_excel(url)

In [11]:
enrollies.head()

   enrollee_id      full_name      city gender
0         8949     Mike Jones  city_103   Male
1        29725    Laura Jones   city_40   Male
2        11561   David Miller   city_21    NaN
3        33241    Laura Davis  city_115    NaN
4          666  Alex Martinez  city_162   Male

## 1.2 Enrollies' Education data import

In [12]:
enrollies_education = pd.read_excel('https://assets.swisscoding.edu.vn/company_course/enrollies_education.xlsx')

In [13]:
enrollies_education.head()

   enrollee_id enrolled_university education_level major_discipline
0         8949       no_enrollment        Graduate             STEM
1        29725       no_enrollment        Graduate             STEM
2        11561    Full time course        Graduate             STEM
3        33241                 NaN        Graduate  Business Degree
4          666       no_enrollment         Masters             STEM

## 1.3 Enrollies's work experience

In [14]:
# Import needed library to download data from google drive
import requests

google_redirect_url = 'https://assets.swisscoding.edu.vn/company_course/work_experience.csv'

# Download needed file automatically from google url
try:
    response = requests.get(google_redirect_url, allow_redirects=True)

    # Check if the request was successful after following redirects
    if response.status_code == 200:
        with open('work_experience.csv', 'wb') as f:
            f.write(response.content)
        print("work_experience.csv downloaded successfully.")
    else:
        print(f"Failed to download work_experience.csv. Status code: {response.status_code}")
except requests.exceptions.RequestException as e:
    print(f"An error occurred during the request: {e}")

work_experience.csv downloaded successfully.

In [15]:
# Import work experience data
enrollies_work_experience = pd.read_csv('work_experience.csv')

In [16]:
# Show first 5 rows of the table
enrollies_work_experience.head()

,enrollee_id,relevent_experience,experience,company_size,company_type,last_new_job
0,8949,Has relevent experience,>20,NaN,NaN,1
1,29725,No relevent experience,15,50-99,Pvt Ltd,>4
2,11561,No relevent experience,5,NaN,NaN,never
3,33241,No relevent experience,<1,NaN,Pvt Ltd,never
4,666,Has relevent experience,>20,50-99,Funded Startup,4

## 1.4 Training hours data import

In [17]:
# import library to import data from database
from sqlalchemy import create_engine

In [18]:
# Module installation
!pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.1.2)

In [19]:
# Then import SQL connector
import pymysql

In [20]:
# connect to the database via SQL Alchemy engine
engine = create_engine('mysql+pymysql://etl_practice:550814@112.213.86.31:3360/company_course')

In [21]:
# Import training hours data from database
training_hours = pd.read_sql_table('training_hours', con=engine)

In [22]:
# Show first 5 rows of the table
training_hours.head()

   enrollee_id  training_hours
0         8949              36
1        29725              47
2        11561              83
3        33241              52
4          666               8

## 1.5 City development Index data import

In [23]:
# Import all the tables from the html site
html_tables = pd.read_html('https://sca-programming-school.github.io/city_development_index/index.html')

In [24]:
# Retrieve the needed data table for our work
city_index = html_tables[0]

In [25]:
# Show first 5 rows of the table
city_index.head()

       City  City Development Index
0  city_103                   0.920
1   city_40                   0.776
2   city_21                   0.624
3  city_115                   0.789
4  city_162                   0.767

## 1.6 Employment Data import

In [26]:
#import from SQL server that already imported
employment = pd.read_sql_table('employment', con=engine)

In [27]:
# show first 5 rows of the data
employment.head()

   enrollee_id  employed
0            1       0.0
1            2       1.0
2            4       0.0
3            5       0.0
4            7       0.0

# 2. Data Cleaning

## 2.1 Enrollies table

In [28]:
# View the basic information of the dataframe
enrollies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   full_name    19158 non-null  object
 2   city         19158 non-null  object
 3   gender       14650 non-null  object
dtypes: int64(1), object(3)
memory usage: 598.8+ KB

In [29]:
# Change `full name` and `city` columns to `string` Dtype
enrollies['full_name']=enrollies['full_name'].astype('string')
enrollies['city']=enrollies['city'].astype('string')

In [30]:
# Fill null value in gender with 'other' and change to `category` Dtype
enrollies['gender'] = enrollies['gender'].fillna('other').astype('category')

In [31]:
# Check the information again after modifying
enrollies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   full_name    19158 non-null  string
 2   city         19158 non-null  string
 3   gender       19158 non-null  category
dtypes: category(1), int64(1), string(2)
memory usage: 468.1 KB

## 2.2 Enrollies' Education data

In [32]:
# View the basic information of the dataframe
enrollies_education.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   enrolled_university  18772 non-null  object
 2   education_level      18698 non-null  object
 3   major_discipline     16345 non-null  object
dtypes: int64(1), object(3)
memory usage: 598.8+ KB

In [33]:
# Change Dtype accordingly
enrollies_education['enrolled_university'] = enrollies_education['enrolled_university'].astype('string')
enrollies_education['major_discipline'] = enrollies_education['major_discipline'].astype('string')
enrollies_education['education_level'] = enrollies_education['education_level'].astype('string')

In [34]:
# Fill null value with 'unknown' and change Dtype accordingly
enrollies_education['enrolled_university'] = enrollies_education['enrolled_university'].fillna('unknown')
discipline_value = 'unknown'
education_value = 'unknown'
enrollies_education['major_discipline'] = enrollies_education['major_discipline'].fillna(discipline_value).astype('category')
enrollies_education['education_level'] = enrollies_education['education_level'].fillna(education_value).astype('category')

In [35]:
# Check the information again after changing
enrollies_education.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   enrolled_university  19158 non-null  string
 2   education_level      19158 non-null  category
 3   major_discipline     19158 non-null  category
dtypes: category(2), int64(1), string(1)
memory usage: 337.5 KB

## 2.3 Enrollies's Work experience

In [36]:
# View the basic information of the dataframe
enrollies_work_experience.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   relevent_experience  19158 non-null  object
 2   experience           19093 non-null  object
 3   company_size         13220 non-null  object
 4   company_type         13018 non-null  object
 5   last_new_job         18735 non-null  object
dtypes: int64(1), object(5)
memory usage: 898.2+ KB

In [37]:
# Change Dtype accordingly
enrollies_work_experience['relevent_experience'] = enrollies_work_experience['relevent_experience'].astype('string')
enrollies_work_experience['experience'] = enrollies_work_experience['experience'].astype('string')
enrollies_work_experience['company_type'] = enrollies_work_experience['company_type'].astype('string')
enrollies_work_experience['company_size'] = enrollies_work_experience['company_size'].astype('string')
enrollies_work_experience['last_new_job'] = enrollies_work_experience['last_new_job'].astype('string')

In [38]:
# Fill null value with 'unknown' and change Dtype accordingly
enrollies_work_experience['experience'] = enrollies_work_experience['experience'].fillna('unknown')
enrollies_work_experience['company_type'] = enrollies_work_experience['company_type'].fillna(enrollies_work_experience['company_type'].mode()[0]).astype('category')
enrollies_work_experience['company_size'] = enrollies_work_experience['company_size'].fillna(enrollies_work_experience['company_size'].mode()[0])
enrollies_work_experience['last_new_job'] = enrollies_work_experience['last_new_job'].fillna('unknown')

In [39]:
# Check the information again after changing
enrollies_work_experience.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   relevent_experience  19158 non-null  string
 2   experience           19158 non-null  string
 3   company_size         19158 non-null  string
 4   company_type         19158 non-null  category
 5   last_new_job         19158 non-null  string
dtypes: category(1), int64(1), string(4)
memory usage: 767.4 KB

## 2.4 City Development Index

In [40]:
# View the basic information of dataframe
city_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   City                    123 non-null    object
 1   City Development Index  123 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.1+ KB

In [41]:
# Rename the columns accordingly for better management and change Dtype
city_index = city_index.rename(columns={'City': 'city'}).astype('string')
city_index = city_index.rename(columns={'City Development Index': 'city_development_index'})

In [42]:
# Check the information again after changing
city_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   city                    123 non-null    string
 1   city_development_index  123 non-null    string
dtypes: string(2)
memory usage: 2.1 KB

## 2.5 Training hours data

In [43]:
training_hours.info()
# No error found

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   enrollee_id     19158 non-null  int64
 1   training_hours  19158 non-null  int64
dtypes: int64(2)
memory usage: 299.5 KB

##2.6 Employment data

In [44]:
employment.info()
# No error found

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   employed     19158 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 299.5 KB

# Merge all tables

In [45]:
#Create a dataframe with a copy of the enrollies table
df = enrollies.copy()

In [46]:
#Merge enrollies education talbe into the main dataframe
df = df.merge(enrollies_education, on='enrollee_id', how='left')

In [47]:
# Merge enrollies work experience table into the main dataframe
df = df.merge(enrollies_work_experience, on='enrollee_id', how='left')

In [48]:
# Merge training hours table into the main dataframe
df = df.merge(training_hours, on='enrollee_id', how='left')

In [49]:
# Merge the city index table into the main dataframe
df = df.merge(city_index, on='city', how='left')

In [50]:
# Show the first 5 rows of the total merged table
df.head()

,enrollee_id,full_name,city,gender,enrolled_university,education_level,major_discipline,relevent_experience,experience,company_size,company_type,last_new_job,training_hours,city_development_index
0,8949,Mike Jones,city_103,Male,no_enrollment,Graduate,STEM,Has relevent experience,>20,50-99,Pvt Ltd,1,36,0.92
1,29725,Laura Jones,city_40,Male,no_enrollment,Graduate,STEM,No relevent experience,15,50-99,Pvt Ltd,>4,47,0.7759999999999999
2,11561,David Miller,city_21,other,Full time course,Graduate,STEM,No relevent experience,5,50-99,Pvt Ltd,never,83,0.624
3,33241,Laura Davis,city_115,other,unknown,Graduate,Business Degree,No relevent experience,<1,50-99,Pvt Ltd,never,52,0.789
4,666,Alex Martinez,city_162,Male,no_enrollment,Masters,STEM,Has relevent experience,>20,50-99,Funded Startup,4,8,0.767

# Load Data to data warehouse

In [51]:
# Create an engine object to connect to the database
warehouse_engine = create_engine('mysql+pymysql://etl:488579@112.213.86.31:3360/data_warehouse')

In [52]:
# Write DataFrames to database
enrollies.to_sql('enrollies', con=warehouse_engine, if_exists='replace', index=False)
enrollies_education.to_sql('enrollies_education', con=warehouse_engine, if_exists='replace', index=False)
enrollies_work_experience.to_sql('enrollies_work_experience', con=warehouse_engine, if_exists='replace', index=False)
city_index.to_sql('city_index', con=warehouse_engine, if_exists='replace', index=False)
training_hours.to_sql('training_hours', con=warehouse_engine, if_exists='replace', index=False)
employment.to_sql('employment', con=warehouse_engine, if_exists='replace', index=False)

19158